Strings/strings.resx
=> Add text entries for favorite replays in the replay menu

Strings/strings.resx
The next PR for RogueEssence will need this.
=> Change text for favorites option

Strings/strings.resx
Adds the string for the main PR: https://github.com/RogueCollab/RogueEssence/pull/19
=> Add string MENU_REPLAY_VERIFY

Strings/strings.resx
DLG_REPLAY_VERIFY_DESYNC
DLG_REPLAY_VERIFY_OK
For PR https://github.com/RogueCollab/RogueEssence/pull/19
=> Added 2 strings

Strings/strings.resx
Option string required for move preview option in this [PR](https://github.com/RogueCollab/RogueEssence/pull/22).
=> Add Preview string

Strings/strings.resx
Menu timer string required by this [PR](https://github.com/RogueCollab/RogueEssence/pull/30).
=> add menu time string

Data/Script/ground/test_grounds/init.lua
Dependent on this [PR](https://github.com/RogueCollab/RogueEssence/pull/77).
=> Text sound example

Strings/strings.resx
Required for this [PR](https://github.com/RogueCollab/RogueEssence/pull/79)
Also capitalized one of the letters in the strings for consistency
=> reset moveset string

Data/Script/menu/SkillSelectMenu.lua
Requires [ScriptableMenu.Draw](https://github.com/RogueCollab/RogueEssence/pull/85) commit to work properly
=> Created SkillSelectMenu.lua

Data/Script/ground/base_camp_2/base_camp_2_juice.lua, Data/Script/menu/InventorySelectMenu.lua, Data/Script/menu/JuiceShopMenu.lua, Strings/strings.resx
Requires https://github.com/RogueCollab/RogueEssence/pull/97 to work
=> Juice menu added

Data/Script/ground/garden_end/init.lua
Adds dungeon dialogue for Shaymin
=> secret garden ally interact event

Data/Script/ground/luminous_spring/init.lua, Data/Script/menu/team/AssemblySelectMenu.lua
Also contains tiny improvement to AssemblySelectMenu builtin instantiators
=> Spring now uses AssemblySelectMenu

Data/Script/ai/ground_partner.lua
Partner will not trail behind as much now if you start running after having been walking.
=> Improve partner following

Data/Script/menu/skill/SkillTutorMenu.lua, Strings/strings.resx
I REALLY didn't test that part of it thoroughly enough. There were multiple parts that were just broken. Thankfully they were only hit when money was involved.
Also fixed moves order being random when calling runTutorMenu
=> Fixed SkillTutorMenu's money handling

Data/Script/origin/services/menu_tools/init.lua, MODS/Enable_Mission_Board/Data/Script/enable_mission_board/services/mission_menu_tools/init.lua
Needs https://github.com/RogueCollab/RogueEssence/pull/116
=> Use Import and Export calls

MODS/Enable_Mission_Board/Data/Script/enable_mission_board/common.lua
I don't know how this one happened but it's probably best if we get rid of it.
=> Fix writing mistake

Data/Script/origin/menu/juice/JuiceShopMenu.lua
More space for text on the right-hand side
=> Juice preview fix

Data/Script/origin/menu/DescriptionSummary.lua
I realized it doesn't use the full box and i hate it.
=> Fix text bounds

Data/Script/origin/ground/base_camp_2/base_camp_2_tutor.lua, Data/Script/origin/menu/skill/SkillTutorMenu.lua
- Allow the menu to check storage items as well
- Make the currently used instance look for heart scales in storage
=> Tutor upgrade

Data/Script/origin/menu/DescriptionSummary.lua, Data/Script/origin/menu/InventorySelectMenu.lua, Data/Script/origin/menu/juice/JuiceShopMenu.lua, Data/Script/origin/menu/juice/SpecialtiesMenu.lua, Data/Script/origin/menu/skill/SkillSelectMenu.lua, Data/Script/origin/menu/skill/SkillTutorMenu.lua, Data/Script/origin/menu/team/AssemblySelectMenu.lua, Data/Script/origin/menu/team/TeamSelectMenu.lua, Data/Script/origin/recruit_list.lua
=> Label lua menus

Data/Skill/scald.json
The issue number refers to the issue on the PMDODump repo.
=> Scald thaws frozen targets (#486)
